[ids]
*

[main]

capslock = overload(layer3, esc)
rightalt = esc
rightshift = -

1 = f1
2 = f2
3 = f3
4 = f4
5 = f5
6 = f6
7 = f7
8 = f8
9 = f9
0 = f10
- = f11
= = f12

[layer3]

rightalt = @
enter = =
leftalt = 0
rightshift = _

z = 1
x = 2
c = 3
a = 4
s = 5
d = 6
q = 7
w = 8
e = 9

r = backspace
t = delete
y = ^
u = +
i = *
o = ~
p = %
[ = (
] = )
\ = &

f = home
g = end
h = left
l = right
k = up
j = down
; = !
' = `

v = pageup
b = pagedown
n = #
m = $

