general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 10

[mouse]
hide_when_typing = true

[window]
padding.x = 14
padding.y = 14
opacity = 0.98
decorations = "None"
option_as_alt = "OnlyLeft"

[scrolling]
history = 100000

[keyboard]
bindings = [
  { action = "ScrollPageUp", key = "PageUp" },
  { action = "ScrollPageDown", key = "PageDown" },
  { action = "First", key = "Home", mode = "Vi" },
  { action = "Last", key = "End", mode = "Vi" },
]

[terminal.shell]
program = "/usr/bin/fish"
args = ["-l"]

# This works in combination with ``~/.config/fish/fish.config`
# and `~/scripts/nvim-remote-open` to enable nvim to open files
# displayed in terminal in the existing editor by pressing ctrl+alt+o
# and choosing the file. If no nvim instance is open it'll start
# a terminal in a new window.
[[hints.enabled]]
command = "nvim-remote-open"
hyperlinks = false
post_processing = false
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift|Alt" }
# Regex to minimize false positives on filepaths
# /*               Optionally start with forward slash
# [a-zA-Z]+        Must start with a letter (remomves e.g. 4.0k)
# [\\w_/-]*        Any combination of valid file path chars
# \\.[\\w_/-]+     Contains a `.` and is followed by at least one valid char
# :*[0-9]*:*[0-9]* Include file/line number if they exist
regex = "/*[a-zA-Z]+[\\w_/-]*\\.[\\.\\w_/-]+:*[0-9]*:*[0-9]*"

